### You need the VSCode REST Client Extension to use this requests

### List all the messages
GET http://localhost:3000/messages

### Create a new message
POST http://localhost:3000/messages
content-type: application/json

{
  "content": "Message after adding DI"
}

### Get a specific message

### Exception / Not found:
GET http://localhost:3000/messages/20
### Returning a message:
GET http://localhost:3000/messages/616
